language: csharp
mono: none
dotnet: 3.1
before_install:
  - sudo apt-get install dotnet-sdk-2.1
install: dotnet restore
jobs:
  include:
  - stage: test
    name: Unit Tests
    script: dotnet test YASDM.Model.Tests/YASDM.Model.Tests.csproj /p:CollectCoverage=true
      /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
    after_success:
      script: ./upload-coveralls.sh

   