language: csharp
mono: none
dotnet: 3.1
jobs:
  include:
    - stage: restore
      script: dotnet restore
    - stage: test
      name: "Unit Tests"
      script: dotnet test YASDM.Model.Tests/YASDM.Model.Tests.csproj