language: csharp
mono: none
dotnet: 3.1
before_install:
  - sudo apt-get install dotnet-sdk-2.1
  - export REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - export REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - export REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
install: dotnet restore
jobs:
  include:
  - stage: test
    name: Unit Tests
    script: dotnet test YASDM.Model.Tests/YASDM.Model.Tests.csproj /p:CollectCoverage=true
      /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
    after_success:
      - ./upload-coveralls.sh

   