language: csharp
mono: none
dotnet: 3.1
before_install:
  - sudo apt-get install dotnet-sdk-2.1
install: dotnet restore
jobs:
  include:
  - stage: test
    name: Unit Tests
    script: dotnet test YASDM.Model.Tests/YASDM.Model.Tests.csproj /p:CollectCoverage=true
      /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    after_success:
      - dotnet tool install coveralls.net --version 1.0.0
      - "./tools/csmacnz.Coveralls --opencover -i YASDM.Model.Tests/TestResults/coverage.opencover.xml -r $COVERALL_REPO_TOKEN > /dev/null 2>&1 "
   